INSERT INTO productos (producto, precio_unitario, id_descuento, id_plataforma, rutavideo, iframetrailer, descripcion) VALUES
    ('Persona 5', '49.99', 1, 1, CONCAT('../assets/jokin/1/', id, '.webm'), 'https://www.youtube.com/watch?v=QnDzJ9KzuV4', 'Descripción de Persona 5'),
    ('Red Dead Redemption 2', '59.99', 2, 2, CONCAT('../assets/jokin/2/', id, '.webm'), 'https://www.youtube.com/watch?v=MyaYlbizpvs', 'Descripción de Red Dead Redemption 2'),
    ('Elden Ring', '69.99', 3, 3, CONCAT('../assets/jokin/3/', id, '.webm'), 'https://www.youtube.com/watch?v=CptaXqVY6-E', 'Descripción de Elden Ring'),
    ('Half Life', '19.99', 4, 4, CONCAT('../assets/jokin/4/', id, '.webm'), 'https://www.youtube.com/watch?v=O2W0N3uKXmo', 'Descripción de Half Life'),
    ('The Legend of Zelda', '49.99', 5, 5, CONCAT('../assets/jokin/5/', id, '.webm'), 'https://www.youtube.com/watch?v=ofH5ptn5w-A', 'Descripción de The Legend of Zelda'),
    ('Baldurs Gate', '39.99', 1, 4, CONCAT('../assets/jokin/4/', id, '.webm'), 'https://www.youtube.com/watch?v=OcP0WdH7rTs', 'Descripción de Baldurs Gate'),
    ('Super Mario Odyssey', '54.99', 2, 5, CONCAT('../assets/jokin/5/', id, '.webm'), '../assets/jokin/5/7.webm', 'Descripción de Super Mario Odyssey'),
    ('Super Smash Bros', '59.99', 3, 1, CONCAT('../assets/jokin/1/', id, '.webm'), '../assets/jokin/1/8.webm', 'Descripción de Super Smash Bros'),
    ('The Last of Us', '44.99', 4, 2, CONCAT('../assets/jokin/2/', id, '.webm'), '../assets/jokin/2/9.webm', 'Descripción de The Last of Us'),
    ('Starcraft II', '29.99', 5, 4, CONCAT('../assets/jokin/4/', id, '.webm'), '../assets/jokin/4/10.webm', 'Descripción de Starcraft II'),
    ('Grand Theft Auto V', '39.99', 2, 1, CONCAT('../assets/jokin/1/', id, '.webm'), '../assets/jokin/1/11.webm', 'Descripción de Grand Theft Auto V'),
    ('Divinity Original Sin', '29.99', 3, 4, CONCAT('../assets/jokin/4/', id, '.webm'), '../assets/jokin/4/12.webm', 'Descripción de Divinity Original Sin'),
    ('Portal 2', '14.99', 4, 1, CONCAT('../assets/jokin/1/', id, '.webm'), '../assets/jokin/1/13.webm', 'Descripción de Portal 2'),
    ('Forza Horizon 4', '49.99', 1, 2, CONCAT('../assets/jokin/2/', id, '.webm'), '../assets/jokin/2/14.webm', 'Descripción de Forza Horizon 4'),
    ('Skyrim', '29.99', 5, 3, CONCAT('../assets/jokin/3/', id, '.webm'), '../assets/jokin/3/15.webm', 'Descripción de Skyrim'),
    ('Sekiro Shadows Die Twice', '59.99', 1, 2, CONCAT('../assets/jokin/2/', id, '.webm'), '../assets/jokin/2/16.webm', 'Descripción de Sekiro Shadows Die Twice'),
    ('BioShock', '39.99', 2, 1, CONCAT('../assets/jokin/1/', id, '.webm'), '../assets/jokin/1/17.webm', 'Descripción de BioShock'),
    ('God of War', '49.99', 3, 2, CONCAT('../assets/jokin/2/', id, '.webm'), '../assets/jokin/2/18.webm', 'Descripción de God of War'),
    ('Metroid Prime', '44.99', 4, 3, CONCAT('../assets/jokin/3/', id, '.webm'), '../assets/jokin/3/19.webm', 'Descripción de Metroid Prime'),
    ('Mass Effect 2', '34.99', 5, 4, CONCAT('../assets/jokin/4/', id, '.webm'), '../assets/jokin/4/20.webm', 'Descripción de Mass Effect 2');
