INSERT INTO productos (producto, precio_unitario, id_descuento, id_plataforma, rutavideo, iframetrailer, descripcion) VALUES
    ('Persona 5', '49.99', 1, 1, '/imgs/1/1.webm', 'https://www.youtube.com/watch?v=QnDzJ9KzuV4', 'Descripción de Persona 5'),
    ('Red Dead Redemption 2', '59.99', 2, 2, '/imgs/2/1.webm', 'https://www.youtube.com/watch?v=MyaYlbizpvs', 'Descripción de Red Dead Redemption 2'),
    ('Elden Ring', '69.99', 3, 3, '/imgs/3/1.webm', 'https://www.youtube.com/watch?v=CptaXqVY6-E', 'Descripción de Elden Ring'),
    ('Half Life', '19.99', 4, 4, '/imgs/4/1.webm', 'https://www.youtube.com/watch?v=O2W0N3uKXmo', 'Descripción de Half Life'),
    ('The Legend of Zelda', '49.99', 5, 5, '/imgs/5/1.webm', 'https://www.youtube.com/watch?v=ofH5ptn5w-A', 'Descripción de The Legend of Zelda'),
    ('Baldurs Gate', '39.99', 1, 4, '/imgs/6/1.webm', 'https://www.youtube.com/watch?v=OcP0WdH7rTs', 'Descripción de Baldurs Gate'),
    ('Super Mario Odyssey', '54.99', 2, 5, '/imgs/7/1.webm', 'https://www.youtube.com/watch?v=EF5YynyWvQo', 'Descripción de Super Mario Odyssey'),
    ('Super Smash Bros', '59.99', 3, 1, '/imgs/8/1.webm', 'https://www.youtube.com/watch?v=tqSY9mlmWIs', 'Descripción de Super Smash Bros'),
    ('The Last of Us', '44.99', 4, 2, '/imgs/9/1.webm', 'https://www.youtube.com/watch?v=Mel8DZBEJTo', 'Descripción de The Last of Us'),
    ('Starcraft II', '29.99', 5, 4, '/imgs/10/1.webm', 'https://www.youtube.com/watch?v=M_XwzBMTJaM', 'Descripción de Starcraft II'),
    ('Grand Theft Auto V', '39.99', 2, 1, '/imgs/11/1.webm', 'https://www.youtube.com/watch?v=M_XwzBMTJaM', 'Descripción de Grand Theft Auto V'),
    ('Divinity Original Sin', '29.99', 3, 4, '/imgs/12/1.webm', 'https://www.youtube.com/watch?v=Mea7Pa3rhJU', 'Descripción de Divinity Original Sin'),
    ('Portal 2', '14.99', 4, 1, '/imgs/13/1.webm', 'https://www.youtube.com/watch?v=tax4e4hBBZc', 'Descripción de Portal 2'),
    ('Forza Horizon 4', '49.99', 1, 2, '/imgs/14/1.webm', 'https://www.youtube.com/watch?v=FYH9n37B7Yw', 'Descripción de Forza Horizon 4'),
    ('Skyrim', '29.99', 5, 3, '/imgs/15/1.webm', 'https://www.youtube.com/watch?v=ElzKoBRZjd4', 'Descripción de Skyrim'),
    ('Sekiro Shadows Die Twice', '59.99', 1, 2, '/imgs/16/1.webm', 'https://www.youtube.com/watch?v=rXMX4YJ7Lks', 'Descripción de Sekiro Shadows Die Twice'),
    ('BioShock', '39.99', 2, 1, '/imgs/17/1.webm', 'https://www.youtube.com/watch?v=QQ825MfC-AU', 'Descripción de BioShock'),
    ('God of War', '49.99', 3, 2, '/imgs/18/1.webm', 'https://www.youtube.com/watch?v=jb0LtQBNqhY', 'Descripción de God of War'),
    ('Metroid Prime', '44.99', 4, 3, '/imgs/19/1.webm', 'https://www.youtube.com/watch?v=PW4a7ZvqRaw', 'Descripción de Metroid Prime'),
    ('Mass Effect 2', '34.99', 5, 4, '/imgs/20/1.webm', 'https://www.youtube.com/watch?v=xNcmIsPdqBw', 'Descripción de Mass Effect 2');
INSERT INTO productos (producto, precio_unitario, id_descuento, id_plataforma, rutavideo, iframetrailer, descripcion)
VALUES
    ('The Witcher 3 Wild Hunt', 48.99 , 1, 1, 'ruta_video_witcher', 'iframe_witcher', 'Descripción The Witcher 3 Wild Hunt'),
    ('Street Fighter', 24.99 ,1, 2, 'ruta_video_street_fighter', 'iframe_street_fighter', 'Descripción Street Fighter'),
    ('Divinity Original Sin', 9.99 ,1, 3, 'ruta_video_divinity', 'iframe_divinity', 'Descripción Divinity Original Sin'),
    ('Uncharted 4', 18.46 ,1, 4, 'ruta_video_uncharted', 'iframe_uncharted', 'Descripción Uncharted 4'),
    ('AstroBot', 5.99 ,1, 5, 'ruta_video_astrobot', 'iframe_astrobot', 'Descripción AstroBot'),
    ('Ori and the Wild of the Wisps', 28.55 ,1, 6, 'ruta_video_ori', 'iframe_ori', 'Descripción Ori and the Wild of the Wisps'),
    ('Operation Flashpoint', 56.85 ,1, 7, 'ruta_video_operation_flashpoint', 'iframe_operation_flashpoint', 'Descripción Operation Flashpoint'),
    ('Dota 2', 15.99 ,1, 8, 'ruta_video_dota2', 'iframe_dota2', 'Descripción Dota 2'),
    ('League of Legends', 15.99 ,1, 9, 'ruta_video_lol', 'iframe_lol', 'Descripción League of Legends'),
    ('Rise Son of Rome', 8.99 , 1, 1, 'ruta_video_rise_son_of_rome', 'iframe_rise_son_of_rome', 'Descripción Rise Son of Rome'),
    ('Dark Souls', 12.99 , 1, 2, 'ruta_video_dark_souls', 'iframe_dark_souls', 'Descripción Dark Souls'),
    ('Final Fantasy XIV', 50.12 , 1, 3, 'ruta_video_final_fantasy_xiv', 'iframe_final_fantasy_xiv', 'Descripción Final Fantasy XIV'),
    ('Fez', 10.65 , 1, 4, 'ruta_video_fez', 'iframe_fez', 'Descripción Fez'),
    ('Bloodborne', 64.55 , 1, 5, 'ruta_video_bloodborne', 'iframe_bloodborne', 'Descripción Bloodborne'),
    ('Dragon Age Inquisition', 75.15 , 1, 6, 'ruta_video_dragon_age_inquisition', 'iframe_dragon_age_inquisition', 'Descripción Dragon Age Inquisition'),
    ('Crysis', 5.99 , 1, 7, 'ruta_video_crysis', 'iframe_crysis', 'Descripción Crysis'),
    ('Fallout 3', 45.24 , 1, 8, 'ruta_video_fallout3', 'iframe_fallout3', 'Descripción Fallout 3'),
    ('Mortal Kombat', 64.99 , 1, 9, 'ruta_video_mortal_kombat', 'iframe_mortal_kombat', 'Descripción Mortal Kombat'),
    ('Resident Evil 2 Remastered', 52.85 , 1, 1, 'ruta_video_resident_evil_2', 'iframe_resident_evil_2', 'Descripción Resident Evil 2 Remastered'),
    ('Dead Cells', 26.84 , 1, 2, 'ruta_video_dead_cells', 'iframe_dead_cells', 'Descripción Dead Cells'),
    ('Metal Gear Solid V', 33.99 , 1, 3, 'ruta_video_metal_gear_solid_v', 'iframe_metal_gear_solid_v', 'Descripción Metal Gear Solid V'),
    ('Max Payne', 2.99 , 1, 4, 'ruta_video_max_payne', 'iframe_max_payne', 'Descripción Max Payne'),
    ('Doom Eternal', 4.99 , 1, 5, 'ruta_video_doom_eternal', 'iframe_doom_eternal', 'Descripción Doom Eternal'),
    ('Dead Space', 12.99 , 1, 6, 'ruta_video_dead_space', 'iframe_dead_space', 'Descripción Dead Space'),
    ('Monster Hunter World', 27.57 , 1, 7, 'ruta_video_monster_hunter_world', 'iframe_monster_hunter_world', 'Descripción Monster Hunter World'),
    ('Warcraft 3', 72.56 , 1, 8, 'ruta_video_warcraft3', 'iframe_warcraft3', 'Descripción Warcraft 3'),
    ('Batman Arkham City', 24.78, 1, 9, 'ruta_video_batman_arkham_city', 'iframe_batman_arkham_city', 'Descripción Batman Arkham City'),
    ('Minecraft', 1.99 , 1, 1, 'ruta_video_minecraft', 'iframe_minecraft', 'Descripción Minecraft'),
    ('Halo Combat Evolved', 15.99 , 1, 2, 'ruta_video_halo_combat_evolved', 'iframe_halo_combat_evolved', 'Descripción Halo Combat Evolved'),
    ('Fortnite', 50.85 , 1, 3, 'ruta_video_fortnite', 'iframe_fortnite', 'Descripción Fortnite');
