INSERT INTO logos (rutalogo, tipo, nombre, id_plataforma, id_maquina)
VALUES
    ('/img/logos/1.png', 'Principal', 'Logo de Persona 5', 1, 1),  
    ('/img/logos/2.png', 'Principal', 'Logo de Red Dead Redemption 2', 2, 2),  
    ('/img/logos/3.png', 'Principal', 'Logo de Elden Ring', 3, 3),   
    ('/img/logos/4.png', 'Principal', 'Logo de Half Life', 4, 4), 
    ('/img/logos/5.png', 'Principal', 'Logo de The Legend of Zelda', 4, 3),  
    ('/img/logos/6.png', 'Principal', 'Logo de Baldurs Gate', 5, 4),  
    ('/img/logos/7.png', 'Principal', 'Logo de Super Mario Odyssey', 4, 1),    
    ('/img/logos/8.png', 'Principal', 'Logo de Super Smash Bros', 3, 2),    
    ('/img/logos/9.png', 'Principal', 'Logo de The Last of Us', 2, 1),    
    ('/img/logos/10.png', 'Principal', 'Logo de Starcraft II', 2, 4), 
    ('/img/logos/11.png', 'Principal', 'Logo de Grand Theft Auto V', 3, 1), 
    ('/img/logos/12.png', 'Principal', 'Logo de Divinity Original Sin', 4, 4),
    ('/img/logos/13.png', 'Principal', 'Logo de Portal 2', 4, 1),    
    ('/img/logos/14.png', 'Principal', 'Logo de Forza Horizon 4', 5, 4),  
    ('/img/logos/15.png', 'Principal', 'Logo de Skyrim', 4, 3),   
    ('/img/logos/16.png', 'Principal', 'Logo de Sekiro Shadows Die Twice', 3, 2),  
    ('/img/logos/17.png', 'Principal', 'Logo de BioShock', 3, 1), 
    ('/img/logos/18.png', 'Principal', 'Logo de God of War', 1, 1),    
    ('/img/logos/19.png', 'Principal', 'Logo de Metroid Prime', 1, 3),  
    ('/img/logos/20.png', 'Principal', 'Logo de Mass Effect 2', 1, 4);    
