"""empty message

Revision ID: 02549e808431
Revises: 4384dae13483
Create Date: 2024-01-23 12:00:28.889357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02549e808431'
down_revision = '4384dae13483'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rutalogo', sa.Integer(), nullable=False),
    sa.Column('id_plataforma', sa.Integer(), nullable=False),
    sa.Column('id_maquina', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_maquina'], ['maquina.id'], ),
    sa.ForeignKeyConstraint(['id_plataforma'], ['plataforma.id'], ),
    sa.PrimaryKeyConstraint('id', 'rutalogo')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['correo'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('logos')
    # ### end Alembic commands ###
