"""empty message

Revision ID: 05c30842dde3
Revises: 
Create Date: 2024-01-26 08:26:52.377084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05c30842dde3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('descuentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descuento', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maquina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maquina', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipopago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipopago', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('apellido', sa.String(length=255), nullable=False),
    sa.Column('correo', sa.String(length=255), nullable=False),
    sa.Column('contrasena', sa.String(length=255), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('metodopago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('direccion_fact', sa.String(length=255), nullable=False),
    sa.Column('nombreCompleto', sa.String(length=60), nullable=False),
    sa.Column('id_metodo', sa.Integer(), nullable=False),
    sa.Column('numero_tarjeta', sa.String(length=24), nullable=False),
    sa.Column('cvv', sa.Integer(), nullable=False),
    sa.Column('titular_tarjeta', sa.String(length=40), nullable=False),
    sa.Column('fecha_caduc', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_metodo'], ['tipopago.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plataforma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plataforma', sa.String(length=60), nullable=False),
    sa.Column('id_maquina', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_maquina'], ['maquina.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resena',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('resena', sa.Text(), nullable=False),
    sa.Column('valoracion', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rutalogo', sa.String(length=255), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('id_plataforma', sa.Integer(), nullable=False),
    sa.Column('id_maquina', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_maquina'], ['maquina.id'], ),
    sa.ForeignKeyConstraint(['id_plataforma'], ['plataforma.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto', sa.String(length=255), nullable=False),
    sa.Column('precio_unitario', sa.String(length=255), nullable=False),
    sa.Column('id_descuento', sa.Integer(), nullable=False),
    sa.Column('id_plataforma', sa.Integer(), nullable=False),
    sa.Column('rutavideo', sa.String(length=255), nullable=False),
    sa.Column('iframetrailer', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_descuento'], ['descuentos.id'], ),
    sa.ForeignKeyConstraint(['id_plataforma'], ['plataforma.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_metodopago', sa.Integer(), nullable=False),
    sa.Column('importe', sa.Double(), nullable=False),
    sa.Column('fechahora', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_metodopago'], ['metodopago.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carrocompra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('pagado', sa.Boolean(), nullable=False),
    sa.Column('isdeleted', sa.Boolean(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imagenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rutaimagen', sa.Text(), nullable=False),
    sa.Column('id_juego', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_juego'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listadeseos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('favorito', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producto_categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_categoria'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producto_resena',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_resena', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['id_resena'], ['resena.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transacionproducto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_transaccion', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Double(), nullable=False),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['id_transaccion'], ['transaccion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transacionproducto')
    op.drop_table('producto_resena')
    op.drop_table('producto_categoria')
    op.drop_table('listadeseos')
    op.drop_table('imagenes')
    op.drop_table('carrocompra')
    op.drop_table('transaccion')
    op.drop_table('productos')
    op.drop_table('logos')
    op.drop_table('resena')
    op.drop_table('plataforma')
    op.drop_table('metodopago')
    op.drop_table('usuarios')
    op.drop_table('tipopago')
    op.drop_table('maquina')
    op.drop_table('descuentos')
    op.drop_table('categorias')
    # ### end Alembic commands ###
