"""empty message

Revision ID: 3d30c3a480df
Revises: d88cd3b93f40
Create Date: 2024-01-19 11:02:07.656622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d30c3a480df'
down_revision = 'd88cd3b93f40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metodopago', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cvv', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('titular_tarjeta', sa.String(length=40), nullable=False))

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contrasena', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('contrasena')

    with op.batch_alter_table('metodopago', schema=None) as batch_op:
        batch_op.drop_column('titular_tarjeta')
        batch_op.drop_column('cvv')

    # ### end Alembic commands ###
