"""empty message

Revision ID: 78c0ec573cff
Revises: 6bbe01a35c6c
Create Date: 2024-01-25 12:03:40.269003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78c0ec573cff'
down_revision = '6bbe01a35c6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ventas', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('ventas')

    # ### end Alembic commands ###
