"""Añadido tabla descuentos

Revision ID: 881add7eace0
Revises: 973767efafa5
Create Date: 2024-01-18 11:41:24.968080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '881add7eace0'
down_revision = '973767efafa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_descuento', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'descuentos', ['id_descuento'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_descuento')

    # ### end Alembic commands ###
