"""ajajajaj2

Revision ID: 973767efafa5
Revises: 
Create Date: 2024-01-18 11:29:43.081863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '973767efafa5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Drop the foreign key constraint first
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_constraint('productos_id_descuento_fkey', type_='foreignkey')
        batch_op.drop_column('id_descuento')

    # Drop the 'descuentos' table after dropping the foreign key
    op.drop_table('descuentos')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_descuento', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('productos_id_descuento_fkey', 'descuentos', ['id_descuento'], ['id'])

    op.create_table('descuentos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('descuento', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='descuentos_pkey')
    )
    # ### end Alembic commands ###
